import type { Metadata } from "next";
import { Geist, Lato, Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
// import Sidebar from "@/components/sidebar";
import { isMobile } from "react-device-detect";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const lato = Lato({
	variable: "--font-lato",
	subsets: ["latin"],
	weight: ["300", "400", "700"],
});

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// const auth = true;
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${lato.variable} ${inter.variable} light antialiased`}
			>
				{!isMobile && <Providers>
					<div className="flex h-screen gap-5">
						{/* {auth && <Sidebar />} */}
						{children}
					</div>
				</Providers>}
				{isMobile && 
					<div className="flex flex-col justify-center items-center h-screen">
						<p className="text-lg font-medium uppercase">Website not available on mobile devices</p>
					</div>
				}
			</body>
		</html>
	);
}
