import type { Metadata } from "next";
import { Geist, Lato, Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import ClientLayoutWrapper from "./client-wrapper";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const lato = Lato({
	variable: "--font-lato",
	subsets: ["latin"],
	weight: ["300", "400", "700"],
});

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	// const auth = true;
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${lato.variable} ${inter.variable} antialiased bg-background overglow-hidden`}
			>
				<Providers>
					<ClientLayoutWrapper>
						<div className="overflow-hidden relative min-h-screen">
							{children}
						</div>
					</ClientLayoutWrapper>
				</Providers>
			</body>
		</html>
	);
}
